version: '3.8'

networks:
    external_network:
        external: true
        name: ${DEFAULT_DOCKER_NETWORK}

services:

    queue:
        image: ${QUEUE_IMAGE}
        hostname: queue_${CONTAINER_NAME_PREFIX}
        container_name: queue_${CONTAINER_NAME_PREFIX}
        env_file:
            - ${DOCKER_PHP_APP_PATH}/.env.container
            - ${DOCKER_PHP_QUEUE_PATH}/.env.container
        volumes:
            - ${DOCKER_PHP_PATH}/configs/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf:ro
            - ${DOCKER_PHP_PATH}/docker-entrypoint.sh:/entrypoint.sh:ro
            # - ${ROOT_PATH}:/var/www/app:delegated
        # Graceful shutdown
        stop_signal: SIGQUIT
        stop_grace_period: 120s
        networks:
            external_network:
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "5"
                mode: "non-blocking"
                tag: "logging-queue"
