version: '3.8'

networks:
    compose_network:
        driver: bridge
        name: ${DEFAULT_DOCKER_NETWORK}

services:

    hello-world:
        image: hello-world:latest
        hostname: hello-world
        container_name: hello-world
        networks:
            compose_network:
